define(['underscore/nyt'], function(_) {

var templates = {};

templates["emailModal"] = function(obj){var __t,__p='',__j=Array.prototype.join,print=function(){__p+=__j.call(arguments,'');};with(obj||{}){__p+='<iframe src="'+((__t=( emailThisUrl ))==null?'':__t)+''+((__t=( dataUrl ))==null?'':__t)+'" title="Email This" id="emailthis" scrolling="'+((__t=( scrolling ))==null?'':__t)+'" marginheight="0" marginwidth="0" frameborder="0"></iframe>';}return __p;};

templates["savemodal"] = function(obj){var __t,__p='',__j=Array.prototype.join,print=function(){__p+=__j.call(arguments,'');};with(obj||{}){__p+='<ul class="instructions">\n<li>This item has been saved to read later from any device. </li>\n<li>Access saved items through your user name at the top of the page.</li>\n</ul>\n<p><a href="'+((__t=( link ))==null?'':__t)+'">View Saved Items</a><p>\n<button class="button dismiss-button">OK</button>';}return __p;};

templates["shareTool"] = function(obj){var __t,__p='',__j=Array.prototype.join,print=function(){__p+=__j.call(arguments,'');};with(obj||{}){__p+='<a href="javascript:;" data-share="'+((__t=(id))==null?'':__t)+'"><i class="icon"></i><span class="sharetool-text '+((__t=( isLabelHidden === true ? 'visually-hidden' : ''))==null?'':__t)+'">'+((__t=(label))==null?'':__t)+'</span></a>';}return __p;};

templates["shareTools"] = function(obj){var __t,__p='',__j=Array.prototype.join,print=function(){__p+=__j.call(arguments,'');};with(obj||{}){__p+='<ul>\n'; _.each(shares, function (share) { __p+='\n<li class="sharetool '+((__t=(share.type))==null?'':__t)+'-sharetool '+((__t=( config[share.type].loginRequired ? 'login-modal-trigger': '' ))==null?'':__t)+'" data-modal-title="'+((__t=( config[share.type].loginModalText || '' ))==null?'':__t)+'">\n<a href="javascript:;" data-share="'+((__t=(share.type))==null?'':__t)+'"><i class="icon"></i><span class="sharetool-text">'+((__t=(share.label))==null?'':__t)+'</span></a>\n</li>\n'; }); __p+='\n</ul>';}return __p;};

templates["shareToolsModal"] = function(obj){var __t,__p='',__j=Array.prototype.join,print=function(){__p+=__j.call(arguments,'');};with(obj||{}){__p+='<div class="section share">\n<ul class="sharetools-menu">\n'+((__t=( standardToolsList ))==null?'':__t)+'\n</ul>\n<form class="short-url-form">\n<div class="control">\n<div class="label-container"><label for="short-url-input">Permalink</label></div>\n<div class="field-container">\n<input id="short-url-input" class="short-url-input text" type="text" name="short-url-input" value="'+((__t=( shortUrl ))==null?'':__t)+'" readonly="readonly" />\n</div>\n</div>\n</form>\n</div><!--close section -->\n<div class="section tools">\n<h4 class="modal-heading">Tools</h4>\n<ul class="sharetools-menu">\n'+((__t=( articleToolsList ))==null?'':__t)+'\n</ul>\n</div><!--close section -->\n<div class="modal-footer">\n<div class="ad show-all-sharetool-modal-ad hidden">\n<small class="ad-sponsor">Article Tools Sponsored By</small>\n</div>\n</div><!-- close modal footer -->';}return __p;};

templates["showAllSharetoolModal"] = function(obj){var __t,__p='',__j=Array.prototype.join,print=function(){__p+=__j.call(arguments,'');};with(obj||{}){__p+='<div class="section share">\n<ul class="sharetools-menu">\n'+((__t=( showAllLinkList ))==null?'':__t)+'\n</ul>\n<form class="short-url-form">\n<div class="control">\n<div class="label-container"><label for="short-url-input">Permalink</label></div>\n<div class="field-container">\n<input id="short-url-input" class="short-url-input text" type="text" name="short-url-input" value="'+((__t=( shortUrl ))==null?'':__t)+'" readonly/>\n</div>\n</div>\n</form>\n</div> <!--close section -->\n<div class="section tools">\n<h5 class="modal-heading"> Tools </h5>\n<ul class="sharetools-menu">\n'+((__t=( showAllToolList ))==null?'':__t)+'\n</ul>\n</div> <!--close section -->\n<div  class="modal-footer">\n<div class="ad show-all-sharetool-modal-ad hidden">\n<small class="ad-sponsor">Article Tools Sponsored By</small>\n</div>\n</div> <!-- close modal footer -->';}return __p;};

templates["showallLinks"] = function(obj){var __t,__p='',__j=Array.prototype.join,print=function(){__p+=__j.call(arguments,'');};with(obj||{}){__p+='<li class="sharetool '+((__t=( shareObj.type ))==null?'':__t)+'-sharetool '+((__t=( config.loginRequired ? 'login-modal-trigger': '' ))==null?'':__t)+'" data-modal-title="'+((__t=( config.loginModalText || '' ))==null?'':__t)+'">\n<a href="javascript:;" data-share="'+((__t=( shareObj.type ))==null?'':__t)+'"><i class="icon"></i>'+((__t=( shareObj.label ))==null?'':__t)+'</a>\n</li>';}return __p;};

return templates;

});